"""init

Revision ID: 052e2e0c047c
Revises: 
Create Date: 2025-08-26 17:40:37.517485

"""
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = '052e2e0c047c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dangerous_lvl', sa.Enum('TRIVIAL', 'LOW', 'MODERATE', 'HIGH', 'DEADLY', name='dangerlevel'), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monster_dangerous_lvl'), 'monster', ['dangerous_lvl'], unique=False)
    op.create_table('spell',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caster_class', sa.Enum('WIZARD', 'SORCERER', 'CLERIC', 'DRUID', 'PALADIN', 'RANGER', 'BARD', 'WARLOCK', name='casterclass'), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('school', sa.Enum('ABJURATION', 'CONJURATION', 'DIVINATION', 'ENCHANTMENT', 'EVOCATION', 'ILLUSION', 'NECROMANCY', 'TRANSMUTATION', name='spellschool'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_caster_class'), 'spell', ['caster_class'], unique=False)
    op.create_index(op.f('ix_spell_school'), 'spell', ['school'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_spell_school'), table_name='spell')
    op.drop_index(op.f('ix_spell_caster_class'), table_name='spell')
    op.drop_table('spell')
    op.drop_index(op.f('ix_monster_dangerous_lvl'), table_name='monster')
    op.drop_table('monster')
    # ### end Alembic commands ###


