"""Move monster languages to translations; add languages_text; drop monster.languages

Revision ID: 1f5c0f946a86
Revises: 6974b79e15fb
Create Date: 2025-09-12 17:20:03.376954

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f5c0f946a86'
down_revision = '6974b79e15fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster', 'languages')
    op.add_column('monster_translations', sa.Column('languages_text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster_translations', 'languages_text')
    op.add_column('monster', sa.Column('languages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


