"""add title to spell

Revision ID: 1febb77928f3
Revises: e9a6ff02d664
Create Date: 2025-08-27 19:10:10.194474

"""
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = '1febb77928f3'
down_revision = 'e9a6ff02d664'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_spell_title'), 'spell', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spell_title'), table_name='spell')
    op.drop_column('spell', 'title')
    # ### end Alembic commands ###


