"""users add lang field

Revision ID: 41cd6d4de9c8
Revises: f5b1e7b095a1
Create Date: 2025-09-02 21:45:30.011184

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401

# revision identifiers, used by Alembic.
revision = '41cd6d4de9c8'
down_revision = 'f5b1e7b095a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lang', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lang')
    # ### end Alembic commands ###


