"""iteration8_add_cr_enum

Revision ID: 5d7dbf11d3b3
Revises: 3e95296652a5
Create Date: 2025-09-01 19:31:56.205106

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision = '5d7dbf11d3b3'
down_revision = '3e95296652a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cr_enum_type = sa.Enum(
        'CR_1_8', 'CR_1_4', 'CR_1_2',
        'CR_1', 'CR_2', 'CR_3', 'CR_4', 'CR_5', 'CR_6', 'CR_7', 'CR_8', 'CR_9', 'CR_10',
        'CR_11', 'CR_12', 'CR_13', 'CR_14', 'CR_15', 'CR_16', 'CR_17', 'CR_18', 'CR_19',
        'CR_20', 'CR_21', 'CR_22', 'CR_23', 'CR_24', 'CR_25', 'CR_26', 'CR_27', 'CR_28',
        'CR_29', 'CR_30',
        name='challengerating'
    )
    bind = op.get_bind()
    cr_enum_type.create(bind, checkfirst=True)
    op.add_column('monster', sa.Column('cr_enum', cr_enum_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop column first, then drop enum type if exists
    op.drop_column('monster', 'cr_enum')
    cr_enum_type = sa.Enum(
        'CR_1_8', 'CR_1_4', 'CR_1_2',
        'CR_1', 'CR_2', 'CR_3', 'CR_4', 'CR_5', 'CR_6', 'CR_7', 'CR_8', 'CR_9', 'CR_10',
        'CR_11', 'CR_12', 'CR_13', 'CR_14', 'CR_15', 'CR_16', 'CR_17', 'CR_18', 'CR_19',
        'CR_20', 'CR_21', 'CR_22', 'CR_23', 'CR_24', 'CR_25', 'CR_26', 'CR_27', 'CR_28',
        'CR_29', 'CR_30',
        name='challengerating'
    )
    bind = op.get_bind()
    cr_enum_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###


