"""remove has_aoe, has_ranget and derived senses

Revision ID: 6974b79e15fb
Revises: a5f6c8b6bcf4
Create Date: 2025-09-12 17:07:43.476216

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision = '6974b79e15fb'
down_revision = 'a5f6c8b6bcf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster', 'has_ranged')
    op.drop_column('monster', 'has_truesight')
    op.drop_column('monster', 'tremorsense_range')
    op.drop_column('monster', 'blindsight_range')
    op.drop_column('monster', 'darkvision_range')
    op.drop_column('monster', 'has_aoe')
    op.drop_column('monster', 'has_blindsight')
    op.drop_column('monster', 'has_darkvision')
    op.drop_column('monster', 'truesight_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster', sa.Column('truesight_range', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('has_darkvision', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('has_blindsight', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('has_aoe', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('darkvision_range', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('blindsight_range', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('tremorsense_range', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('has_truesight', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('has_ranged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


