"""add enum_translations table

Revision ID: 7148f7999c97
Revises: c2043e156930
Create Date: 2025-09-01 21:00:17.629816

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision = '7148f7999c97'
down_revision = 'c2043e156930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'enum_translations',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('enum_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('enum_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('lang', sa.Enum('RU', 'EN', name='language', native_enum=False), nullable=False),
        sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('synonyms', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('enum_type', 'enum_value', 'lang', name='uq_enum_translation_lang')
    )
    op.create_index(op.f('ix_enum_translations_enum_type'), 'enum_translations', ['enum_type'], unique=False)
    op.create_index(op.f('ix_enum_translations_enum_value'), 'enum_translations', ['enum_value'], unique=False)
    op.create_index(op.f('ix_enum_translations_lang'), 'enum_translations', ['lang'], unique=False)
    op.create_index(op.f('ix_enum_translations_label'), 'enum_translations', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enum_translations_label'), table_name='enum_translations')
    op.drop_index(op.f('ix_enum_translations_lang'), table_name='enum_translations')
    op.drop_index(op.f('ix_enum_translations_enum_value'), table_name='enum_translations')
    op.drop_index(op.f('ix_enum_translations_enum_type'), table_name='enum_translations')
    op.drop_table('enum_translations')
    # ### end Alembic commands ###


