"""i18n: drop localized fields from base tables

Revision ID: 7b3bf0ff5679
Revises: a1b2c3d4e5f6
Create Date: 2025-09-04 21:53:47.650382

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b3bf0ff5679'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster', 'name_ru')
    op.drop_column('monster', 'traits')
    op.drop_column('monster', 'name')
    op.drop_column('monster', 'legendary_actions')
    op.drop_column('monster', 'description')
    op.drop_column('monster', 'actions')
    op.drop_column('monster', 'spellcasting')
    op.drop_column('monster', 'reactions')
    op.drop_column('monster', 'name_en')
    op.drop_column('spell', 'name')
    op.drop_column('spell', 'name_ru')
    op.drop_column('spell', 'description')
    op.drop_column('spell', 'name_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('spell', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('spell', sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('spell', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('monster', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('spellcasting', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('monster', sa.Column('legendary_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('monster', sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('monster', sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


