"""sync FKs after bigint change

Revision ID: 817bc5a29a97
Revises: 4cfa87b1299b
Create Date: 2025-09-02 22:53:53.001113

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision = '817bc5a29a97'
down_revision = '4cfa87b1299b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


