"""spells_add_fast_filters_and_metadata

Revision ID: 8263fcad25be
Revises: 2b7b4926409f
Create Date: 2025-08-31 21:13:26.505569

"""
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = '8263fcad25be'
down_revision = '2b7b4926409f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('is_concentration', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('attack_roll', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('damage_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spell', sa.Column('save_ability', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spell', sa.Column('targeting', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spell', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spell', sa.Column('page', sa.Integer(), nullable=True))
    op.add_column('spell', sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spell', sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spell', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_spell_attack_roll'), 'spell', ['attack_roll'], unique=False)
    op.create_index(op.f('ix_spell_damage_type'), 'spell', ['damage_type'], unique=False)
    op.create_index(op.f('ix_spell_is_concentration'), 'spell', ['is_concentration'], unique=False)
    op.create_index(op.f('ix_spell_name_en'), 'spell', ['name_en'], unique=False)
    op.create_index(op.f('ix_spell_name_ru'), 'spell', ['name_ru'], unique=False)
    op.create_index(op.f('ix_spell_ritual'), 'spell', ['ritual'], unique=False)
    op.create_index(op.f('ix_spell_save_ability'), 'spell', ['save_ability'], unique=False)
    op.create_index(op.f('ix_spell_slug'), 'spell', ['slug'], unique=False)
    op.create_index(op.f('ix_spell_source'), 'spell', ['source'], unique=False)
    op.create_index(op.f('ix_spell_targeting'), 'spell', ['targeting'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spell_targeting'), table_name='spell')
    op.drop_index(op.f('ix_spell_source'), table_name='spell')
    op.drop_index(op.f('ix_spell_slug'), table_name='spell')
    op.drop_index(op.f('ix_spell_save_ability'), table_name='spell')
    op.drop_index(op.f('ix_spell_ritual'), table_name='spell')
    op.drop_index(op.f('ix_spell_name_ru'), table_name='spell')
    op.drop_index(op.f('ix_spell_name_en'), table_name='spell')
    op.drop_index(op.f('ix_spell_is_concentration'), table_name='spell')
    op.drop_index(op.f('ix_spell_damage_type'), table_name='spell')
    op.drop_index(op.f('ix_spell_attack_roll'), table_name='spell')
    op.drop_column('spell', 'slug')
    op.drop_column('spell', 'name_en')
    op.drop_column('spell', 'name_ru')
    op.drop_column('spell', 'page')
    op.drop_column('spell', 'source')
    op.drop_column('spell', 'targeting')
    op.drop_column('spell', 'save_ability')
    op.drop_column('spell', 'damage_type')
    op.drop_column('spell', 'attack_roll')
    op.drop_column('spell', 'is_concentration')
    # ### end Alembic commands ###


