"""create ui_translations table

Revision ID: a1b2c3d4e5f6
Revises: 817bc5a29a97
Create Date: 2025-09-03 00:20:00.000000

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '8927cb379ac4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ui_translations',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('lang', sa.Enum('RU', 'EN', name='language', native_enum=False), nullable=False),
        sa.Column('text', sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('namespace', 'key', 'lang', name='uq_ui_translation_lang'),
    )
    op.create_index(op.f('ix_ui_translations_namespace'), 'ui_translations', ['namespace'], unique=False)
    op.create_index(op.f('ix_ui_translations_key'), 'ui_translations', ['key'], unique=False)
    op.create_index(op.f('ix_ui_translations_lang'), 'ui_translations', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ui_translations_lang'), table_name='ui_translations')
    op.drop_index(op.f('ix_ui_translations_key'), table_name='ui_translations')
    op.drop_index(op.f('ix_ui_translations_namespace'), table_name='ui_translations')
    op.drop_table('ui_translations')
    # ### end Alembic commands ###


