"""i18n: add translation tables and Language enum

Revision ID: c2043e156930
Revises: 83c8bdcdfbb1
Create Date: 2025-09-01 20:17:41.503223

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision = 'c2043e156930'
down_revision = '83c8bdcdfbb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_translations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Enum('RU', 'EN', name='language'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_id', 'lang', name='uq_monster_translation_lang')
    )
    op.create_table('spell_translations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Enum('RU', 'EN', name='language'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spell_id', 'lang', name='uq_spell_translation_lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spell_translations')
    op.drop_table('monster_translations')
    # ### end Alembic commands ###


