"""add title to monster

Revision ID: e9a6ff02d664
Revises: 052e2e0c047c
Create Date: 2025-08-27 18:40:08.199631

"""
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = 'e9a6ff02d664'
down_revision = '052e2e0c047c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_monster_title'), 'monster', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monster_title'), table_name='monster')
    op.drop_column('monster', 'title')
    # ### end Alembic commands ###


