"""make titles required for monster and spell

Revision ID: f4ba2cddd45e
Revises: 1febb77928f3
Create Date: 2025-08-27 19:16:52.390437

"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision = 'f4ba2cddd45e'
down_revision = '1febb77928f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill titles for existing rows to satisfy NOT NULL constraint
    op.execute("UPDATE monster SET title = 'Unknown Monster' WHERE title IS NULL")
    op.execute("UPDATE spell SET title = 'Unknown Spell' WHERE title IS NULL")
    op.alter_column('monster', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('spell', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spell', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('monster', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


