services:
  mongo:
    image: mongo:6
    container_name: monster_parser_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  monster_parser:
    build:
      context: ../..
      dockerfile: scripts/monster_parser/Dockerfile
    container_name: monster_parser_tool
    restart: "no"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=dnd_helper
      - MONGO_COLLECTION=raw_monster_dndsu
      - PYTHONPATH=/app/scripts/monster_parser
    volumes:
      - ../../:/app
    working_dir: /app/scripts/monster_parser
    command: ["python3", "--version"]

volumes:
  mongo_data:
