services:
  postgres-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdb

  api-tests:
    build:
      context: ..
      dockerfile: api/Dockerfile
    depends_on:
      - postgres-test
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdb
      - POSTGRES_HOST=postgres-test
      - POSTGRES_PORT=5432
    # Install pytest and httpx at runtime, apply real migrations, then run tests
    command: sh -lc "pip install -q pytest pytest-asyncio && alembic upgrade head && pytest -q"
    volumes:
      - ./tests:/app/tests:ro


