name: Build and Push Images

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          echo "sha=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dnd-helper-api:latest
            ghcr.io/${{ github.repository_owner }}/dnd-helper-api:${{ steps.meta.outputs.sha }}

      - name: Build and push Bot image
        uses: docker/build-push-action@v6
        with:
          context: bot
          file: bot/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dnd-helper-bot:latest
            ghcr.io/${{ github.repository_owner }}/dnd-helper-bot:${{ steps.meta.outputs.sha }}
